name: simple_candlestick_chart_example
description: Demonstrates how to use the simple_candlestick_chart plugin.
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_candlestick_chart:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/
